use bai_tap;
GO

--1.Thêm cột cấp bậc thành viên dành cho khách hàng
ALTER TABLE KHACHHANG ADD CAPBAC NVARCHAR(15);
GO
--2.Xóa khách hàng có mã khách hàng = 25
DELETE KHACHHANG WHERE MAKHACHHANG = 25;
GO
--3.Biến cục bộ
DECLARE @SOBATKI INT;
SET @SOBATKI = 5 ;
SELECT * FROM DATBAN
WHERE MADATBAN > @SOBATKI;
GO
--4.Cập nhật SDT khách hàng có id = 25. Nếu không có in ra dòng không cập nhật được
UPDATE KHACHHANG SET SDT = 0868814474
WHERE MAKHACHHANG = 25
IF (@@ROWCOUNT = 0)
BEGIN
	PRINT 'KHÔNG DÒNG NÀO ĐƯỢC CẬP NHẬT'
RETURN
END
--5.Cho biết tổng tiền được thanh toán 

BEGIN
DECLARE @TONGTIEN INT=0;
SELECT 
@TONGTIEN=SUM(DONGYEUCAU.THANHTIEN) 
FROM DONGYEUCAU
PRINT 'TONG TIEN = ' + CAST(@TONGTIEN AS VARCHAR(15))
END;
--6.In ra tên nhân viên và mã nhân viên
DECLARE @IDNHANVIEN INT,@NAMENHANVIEN NVARCHAR(50)
SET @IDNHANVIEN = 10
SELECT @NAMENHANVIEN = TENNHANVIEN FROM NHANVIEN
WHERE MANHANVIEN = @IDNHANVIEN
PRINT 'ID NHÂN VIÊN LÀ ' + CAST(@IDNHANVIEN AS NVARCHAR(50))
+ ' VÀ TÊN LÀ ' +@NAMENHANVIEN
GO
--7.IN RA CẤP BẬC THÀNH VIÊN DỰA THEO CHI TIÊU HÓA ĐƠN
SELECT TENKHACHHANG,ID_MAKHACHHANG,TONGHOADON,[CAPBACTHANHVIEN]=
CASE 
	WHEN TONGHOADON = 10000 THEN 1
	WHEN TONGHOADON BETWEEN 10000 AND 20000 THEN 2
	WHEN TONGHOADON > 20000 THEN 3
	ELSE 0.0
	END

FROM YEUCAU,KHACHHANG
WHERE ID_MAKHACHHANG=MAKHACHHANG
ORDER BY TONGHOADON ASC
--8.CHO BIẾT GIÁ MÓN ĂN CÓ MÃ MÓN LÀ 1
BEGIN
DECLARE @TIEN1 INT;
DECLARE @TIEN2 INT;
DECLARE @SOLUONG INT;
SELECT 
@TIEN1 = DONGTHANHTOAN.THANHTIEN,
@SOLUONG= DONGTHANHTOAN.SOLUONG
FROM DONGTHANHTOAN
WHERE ID_MAMON=1;
SET @TIEN2=@TIEN1/@SOLUONG;
PRINT 'GIA CUA MON AN LA =' +CAST(@TIEN2 AS VARCHAR(15));
END;
--9. TĂNG PHỤ PHÍ THÊM 5% VỚI NHỮNG THANH TOÁN <50000 Vnđ
WHILE(SELECT AVG(THANHTIEN) FROM DONGTHANHTOAN) < 50000
		BEGIN
		UPDATE DONGTHANHTOAN 
		SET THANHTIEN = THANHTIEN * 1.05
		IF(SELECT MAX(THANHTIEN) FROM DONGTHANHTOAN)>50000
			BREAK
		ELSE
			CONTINUE
		END
--10.BIẾN TOÀN CỤC
SELECT @@VERSION,@@SERVERNAME,@@ERROR;
GO
--11.IN RA LOẠI MÓN CỦA TỪNG MÃ MÓN
SELECT MAMON,LOAIMON =
CASE ID_MANHOM
	WHEN 1 THEN N'tráng miệng'
	WHEN 2 THEN N'món chính'
	WHEN 3 THEN N'món phụ'
	WHEN 4 THEN N'món khai vị'
	WHEN 5 THEN N'hoa quả'
	ELSE N'chưa phân nhóm'
END
FROM MONAN
ORDER BY ID_MANHOM
--12.TẠO THỦ TỤC ĐẶT LẠI SDT CHO KHÁCH HÀNG
CREATE PROC THAY_SDT @MAKH INT, @SDTMOI INT
AS
UPDATE KHACHHANG
SET SDT=@SDTMOI
WHERE MAKHACHHANG=@MAKH
GO
--THỰC THI
THAY_SDT 2,5556666;
GO
--13.TẠO THỦ TỤC LẤY DỮ LIỆU NHÂN VIÊN
CREATE PROC TIM_KIEM_NHAN_VIEN @TIM_NV INT NULL
AS
SELECT MANHANVIEN,TENNHANVIEN,SDT
FROM NHANVIEN
WHERE MANHANVIEN LIKE @TIM_NV
RETURN (@@rowcount)
GO
--THỰC THI
TIM_KIEM_NHAN_VIEN 5;
GO
--14.LẤY RA CÁC NHÂN VIÊN CÓ MÃ TÙY Ý LỚN HƠN 6
CREATE FUNCTION TIM_NHAN_VIEN (@IDNHANVIEN INT)
RETURNS TABLE
AS 
RETURN (SELECT *FROM NHANVIEN WHERE MANHANVIEN > @IDNHANVIEN)
GO
--THỰC THI
SELECT * FROM TIM_NHAN_VIEN(6);
GO
--15.DÙNG CON TRỎ HIỂN THỊ THÔNG TIN TẤT CẢ NHÂN VIÊN
DECLARE @IDNHANVIEN INT
DECLARE @TENNV NVARCHAR(50)

DECLARE CURSORNHANVIEN CURSOR FOR
SELECT MANHANVIEN,TENNHANVIEN FROM NHANVIEN
OPEN CURSORNHANVIEN
FETCH NEXT FROM CURSORNHANVIEN
		INTO @IDNHANVIEN,@TENNV
WHILE @@FETCH_STATUS=0
BEGIN
	--IN KẾT QUẢ
		PRINT'ID : '+CAST (@IDNHANVIEN AS NVARCHAR(50));
		PRINT'TEN NHAN VIEN : ' + @TENNV;
		FETCH NEXT FROM CURSORNHANVIEN
		INTO @IDNHANVIEN,@TENNV
		END
CLOSE CURSORNHANVIEN
DEALLOCATE CURSORNHANVIEN






